platform :ios, '13.4'

inhibit_all_warnings!

target 'Cuple-List' do
	use_frameworks!
  
  pod 'ReactiveCocoa'
  pod 'DeviceKit'
  pod 'SwiftyStoreKit'
  pod 'SnapKit'
  pod 'MagicalRecord'
  pod 'FFPopup'
  pod 'RevenueCat'
  pod 'Sentry'
  pod 'MGSwipeTableCell'
  pod 'KeychainSwift'
  pod 'CocoaLumberjack'
  pod 'lottie-ios'
  
end

post_install do |pi|
  pi.pods_project.targets.each do |t|
    t.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.4'
      config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = "YES"
      config.build_settings['SWIFT_SUPPRESS_WARNINGS'] = 'YES'
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end
end
